name:                TextAdventureEngine
version:             0.1.0.0
github:              "MarcusVoelker/TextAdventureEngine"
license:             BSD3
author:              "Marcus Völker"
maintainer:          "marcus.voelker@rwth-aachen.de"
copyright:           "2019 Marcus Völker"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MarcusVoelker/TextAdventureEngine#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers
- LParse >= 0.3.1
- proteaaudio
- bytestring
- utf8-string
- filepath
- lens
- gloss

library:
  source-dirs: src
  default-extensions: TupleSections, LambdaCase, TemplateHaskell, MultiParamTypeClasses, TypeSynonymInstances, FunctionalDependencies, FlexibleInstances, AllowAmbiguousTypes
  ghc-options:
  - -O2
  - -Wall
  - -Wno-name-shadowing
  - -Wno-type-defaults

executables:
  TextAdventureEngine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - TextAdventureEngine

tests:
  TextAdventureEngine-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions: ExistentialQuantification
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TextAdventureEngine
